os:
- osx
language: swift
osx_image: xcode11.6
script:
- swift build
- swift test
notifications:
  slack:
    secure: YWk46m7v3MasXFHHSmLrGClI4vOAqEQRXA49mTskZtfetKRqjkB3NOATmffqEsLrXI3ZSDB+Ftlfsmbc3Ac56Z7eVegRu22dB6R2R7JMnRj8fJDdlDaV4egBiOvyxE4qSQnUxgJVgJW0SZ+plHVahZadzWE7k5ReGFhHqs77Vdzjx98xH7eij4c0JCXEIRP83w1l7e4raAOCo2k7ars+nB8iG5lrlCPrvpqO0khMrTDqBl5VPGxzDzaGeKKJVsFFf/RakEo4alQxd7aMGg2C37B7xQDBfpgNYFIR8nFOaRhp/1MzPD6ywiIwHQFua4nV7D9kwVP3yQLsB98EnbhmHbxPtmOmhsN2dBeTiR5xo2jOlFjJ3Pc9yIi5Upe9K3bZWcfYFmj73Mf5K8HfVFFQOtAV3KfEV7+RZQTStTYUrMMffTFJ4lg/BovGsCik0YpWK4bnAkzSNylgZP+Rihm2/nTzqhNcsVfYjFl13FM08pWSS+GA+UsYaIZ1FOyu1vkOp5KUhPlTY/kwGclVVjDIjM8mnszSp15mZpb4f+oqkp8fDPOJVCVGz6n8vPiuTF0adfOkc5B8izQULcZ+/Pa5mrtKpvJLsmWRw4XBxOHDohorhNXARCd5/tmw+BJ7k1wK9DpAgIMS+Vu+gS+npjVXrD54uZ1tFW+CLJS5P/vye14=
